version: '3.9'
services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - ./db/data:/var/lib/postgresql/data

  server:
    build:
      dockerfile: server/dockerfile
      context: .
    command: sh -c "alembic upgrade head && mkdir upload && mkdir upload/photos && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./server:/user
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - db

  client:
    image: node:14.19.1
    command: sh -c "npm install && npm run lint:fix && npm start"
    ports:
      - 3000:3000
    working_dir: /client
    environment:
      - ./client/.env
    volumes:
      - ./client:/client
    depends_on:
      - server
