FROM python:3.9.13
WORKDIR /user 
RUN apt-get -y update
RUN apt-get install -y --fix-missing \
    cmake \
    libgtk2.0-dev 
RUN apt-get clean && rm -rf /tmp/* /var/tmp/*

RUN cd ~ && \
    mkdir -p dlib && \
    git clone -b 'v19.9' --single-branch https://github.com/davisking/dlib.git dlib/ && \
    cd  dlib/ && \
    python3 setup.py install --yes USE_AVX_INSTRUCTIONS
COPY ./server/requirements.txt /user/requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r /user/requirements.txt
COPY ./server /user